name: Powerball Auto Updater

on:
  # Runs at 6:00 AM Los Angeles time year-round.
  # During Daylight Time (PDT) LA=UTC-7 → 13:00 UTC
  # During Standard Time (PST)  LA=UTC-8 → 14:00 UTC
  schedule:
    - cron: "0 13 * * *"   # 06:00 PT when LA is on PDT
    - cron: "0 14 * * *"   # 06:00 PT when LA is on PST
  # Allow manual runs from the Actions tab
  workflow_dispatch: {}

permissions:
  contents: write  # needed if we push changes back

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run updater
        # Adjust this if your script lives in a subfolder
        run: python powerball_updater.py

      # OPTIONAL: commit updated CSV/JSON/etc. back to the repo
      - name: Commit & push changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Powerball data [skip ci]"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          # Limit commits to a folder pattern if you want (uncomment next line):
          # file_pattern: "data/**"

      # OPTIONAL: publish run outputs as an artifact for easy download from the run page
      # - name: Upload data artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: powerball-data
      #     path: data/**
