name: Powerball Auto Updater

on:
  schedule:
    - cron: "0 13 * * *"   # 06:00 Los Angeles during PDT
    - cron: "0 14 * * *"   # 06:00 Los Angeles during PST
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run updater
        run: python .github/workflows/powerball_updater.py --csv data/powerball.csv

      # NEW: sort your CSVs by date after the updater runs
      - name: Sort data by date
        run: python .github/workflows/sort_powerball.py

      - name: Commit & push changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update & sort Powerball data [skip ci]"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          # Optional: only commit data folder
          # file_pattern: "data/**"
